# Generated by Django 4.0.3 on 2022-03-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rate_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film_still',
            options={'verbose_name': 'Кадр из фильма', 'verbose_name_plural': 'Кадры из фильма'},
        ),
    ]
